version: '3.4'

services:
  pivpn_api:
    image: pivpn_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT:-7070}:7070
    restart: unless-stopped
    volumes:
      - ./pipes:/pipes:rw
    env_file:
      - ./.env
