version: '3.4'

services:
  vpnbot:
    image: vpnbot
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DEBUG: ${DEBUG}
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py "]
    ports:
      - 5678:5678
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
